name: Print Hello

on: workflow_dispatch
jobs:
  print-hello:
    # Specify on which operating system we want this workflow to run
    runs-on: ubuntu-20.04
    # The steps that will be excuted
    steps:
    - name: Print
      run: echo "Hello, world!"

name: Checkout

on: workflow_dispatch
jobs:
  checkout-repository:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
